### ISSUE TITLE
New project/folder dropdown option (v0.7.1)

### ISSUE THREAD

**Issue by ITMan101** [vassbo/freeshow#116]
### Issue found
Issue when using the popup action to create a folder or project in the sidebar. You are only able to create a folder when you use the popup on an already created folder to create a subfolder. Right-clicking anywhere else in the sidebar to create a folder does nothing.
Creating a project using the popup will "overwrite" any other projects in the folder. It does not matter the number of projects located in the folder.

### Known working
Creating what I would denote as "base" folders using the button at the bottom.
Creating sub-folders using the popu menu action.
Creating a new project using the button at the bottom.

### Something else observed
When transitioning between a project with content in it and one that is empty, the "show" and "edit" tabs do not update and still keep the content from the project with content.

**Comment by vassbo** [comment]
Thanks. I will fix this issue.

About the last thing: the content in the center can be interacted with using the drawer. That's why it's not "bound" to the project. So it's not supposed to close the main content, only open it when interacting with the project. So this is not an issue. Hope you understand what I mean.
