### ISSUE TITLE
Propresenter 7 import

### ISSUE THREAD

**Issue by levuphucnguyen** [vassbo/freeshow#150]
I cannot import from ProPresenter 7 .pro file

**Comment by vassbo** [comment]
No, I haven't implemented it, because I don't have a file from ProPresenter 7 to work with. But if you could send over a couple .pro files (Here or on mail: dev@freeshow.app), I can see if I can add this feature. 😊

**Comment by abbasou** [comment]
Bruh. I can hook you up with .pro files. Lol
[ProPresenter Files.zip](https://github.com/vassbo/freeshow/files/11604396/ProPresenter.Files.zip)

Let me know if you want anything specific. Also note that you can download ProPresenter 7 for free to try out and perhaps get some ideas.

**Comment by vassbo** [comment]
Previously the ProPresenter data files where stored in easy to read .xml format, but in version 7, they are using Googles Protocol Buffers (Meaning the files are stored as raw encoded binary). But I found a solution and will explain here if anyone is interested 😃:

- Luckily I found this awesome guide: https://greyshirtguy.com/blog/propresenter-7-file-format-part-2/
- Along with this repo of reverse engineered .proto files: https://github.com/greyshirtguy/ProPresenter7-Proto
- Because you need the structure files to decode it: https://stackoverflow.com/a/53726698
- I used this package to decode the binary buffer using the .proto files: https://www.npmjs.com/package/protobufjs

Here is a snippet of the code:
`async function decodeProto(filePath) {
    const root = await protobufjs.load("proto/presentation.proto")

    const Presentation = root.lookupType("Presentation")

    const fileContent = readFileSync(filePath)
    const buffer = Buffer.from(fileContent)
    const message = Presentation.decode(buffer)

    return JSON.stringify(message)
}`

**Comment by vassbo** [comment]
Turns out the .proto files weren't included in the built program, so it didn't work.
But I fixed it and this will work in the next version!
