### ISSUE TITLE
Clear section

### ISSUE THREAD

**Issue by lubomsky** [vassbo/freeshow#166]
How about moving clear buttons above preview and (more important) make them static?
I know there are shortcuts, but from my perspective, non-technical volunteers don't learn and use them.
In a rush it's easier to just click a button, which is present everywhere, like preview and control show buttons.

**Comment by vassbo** [comment]
I have thought about making them "static", that would be better for the user but would take up more vertical space. I think they should stay under the preview becuase when you have multiple outputs their buttons are over the preview.

But that would mean that you would have double up with the same buttons, just one line for clearing and another for changing the output action. Because currently all of the small clear buttons have an action menu as well.

I will think about this, maybe by default they are all just clear buttons, but clicking a toggle button will change them to just "change action page" buttons!

**Comment by lubomsky** [comment]
Yeah, the UI and UX 😃 Often seems to be easy...
Thanks for the answer 😊

**Comment by vassbo** [comment]
I figured I just added some small buttons underneath, so it's easy to clear a layer now. Changing the active layer actions should be done automatically for the most part, but if you want to change manually you still can.
