### ISSUE TITLE
Media is not Looping

### ISSUE THREAD

**Issue by Leensen777** [vassbo/freeshow#178]
It would seem like video media and images (Gifs) are not looping and they go to black after they end.

**Comment by vassbo** [comment]
Images are static so "GIFs" should loop for ever, at least in my testing, there's no way they can end.

- The videos should always loop if they are added as an background, and the slide is played. (Because you almost always want them to loop in that case.)
- They should also always loop when played directly from the drawer.
- They should **not** loop when played from the project, or the center preview. (Because in most cases you play one time videos from here.)

Let me know if you have tried the different options I stated here, and if they loop according to how they should. Also let me know if you have a reason to change this behaviour.

You can toggle the video looping on all playing videos here:
![image](https://github.com/vassbo/freeshow/assets/17619496/2c6b961b-efca-4591-b4e3-6217bdefc85d)
