### ISSUE TITLE
Feature request: Songs library

### ISSUE THREAD

**Issue by macdelacruz** [vassbo/freeshow#183]
This feature request is probably borne out of this issue #152. 

Current scenario: songs are being managed inside the _Songs_ which is just a category of _Shows_. A beginner user who wants to create a new song must use the Quick Lyrics textarea on the New show dialog OR if they miss it, they will have to figure out that they have to switch first from the default _Grid view_ to _Text edit_.

I suggest a Song library feature.

So instead, I think you can add a new object called "Songs" or "Songs Library" that will sit as a tab beside the _Scripture_ tab. This will contain songs with lyrics following the usual Genius Lyrics format `[Verse]`, `[Chorus]` etc. 

Then, just like in Scripture, there will be a button to create new show from this song. This button will parse the lyrics to generate groups and slides, and add it as a new show under _Songs_ category of Shows as well as to the current project.

The Songs in the Song Library aside from the lyrics, can contain Metadata such as the Artist, CCLI etc. I know that this Metadata feature is already  in the Shows, but it should be then moved to this Song Library.

**Comment by vassbo** [comment]
Good suggestion. I just don't think it would be good to add this, I think if would be more confusing than helpful.
It's also not neccesary to use "Quick lyrics" or the "Text edit", people can just add slides and add text in the "Edit" tab.

Also any other presentations use the same format as the songs, they also have groups, and can be edited with the text editor.

I have noticed that EasyWorship has it's own seperate "Songs" and "Presentations", but the problem is that they are more or less the same, so I just ended up using "Songs" for everything.

I suggest the better option would be to add some sort of tutorial screen, letting people know the different special "hidden away" features they can use.

**Comment by macdelacruz** [comment]
Ok, it maybe redundant or confusing. But my idea was a better management of song lyrics. 

Just a little background from where I'm coming:
Without OpenLP/EasyWorship or any of the lyrics projection software available, I used to create lyrics using PowerPoint slides with green background, present them and capture on OBS where I can use the chroma filter to key out the green background so I can apply motion backgrounds. The pain point here was preparing the slides, especially when you have so many songs.

So when you said that it is not necessary to use "Quick Lyrics" or the "Text edit" and just add text on "Edit" tab, I imagine the same pain point I had with creating slides using PowerPoint. 

Also, there are instances in an event, you get suprise requests to show lyrics of a particular song which you might have not prepared the slides for. So the easiest and quickest would be copy pasting the lyrics from the internet, and you'll have all the slides for it instantly. 

Since having a song library is probably going to cause confusion, I just look forward to all the issues on the Text edit being resolved.
