### ISSUE TITLE
Hardware video decoding?

### ISSUE THREAD

**Issue by odlg** [vassbo/freeshow#226]
I was able to enable hardware video decoding on linux by using these arguments:
` --use-gl=egl --enable-features=VaapiVideoDecoder --disable-features=UseChromeOSDirectVideoDecoder`
Found it here: https://www.linuxuprising.com/2021/01/how-to-enable-hardware-accelerated.html

It significantly reduces cpu load when playing background videos, but it happens that freeshow freezes when starting the first video. If it handles the first video it continues to function. How to debug what causes this?

Does windows/mac use hardware video decoding?

**Comment by vassbo** [comment]
I'm pretty sure Windows and MacOS also has support for hardware acceleration.
I guess you could use the dev build and open the developer console with CTRL + SHIFT + I.
But I guess the problem is in Chromium, not FreeShow. Here's a statement I found in an article:

> Using hardware acceleration in Google Chrome allows you to consume media and browse through your daily routine much smoother. That's another thing: if it starts causing freezing and crashing issues, you may need to disable hardware acceleration.
https://www.makeuseof.com/what-is-hardware-acceleration/

Let me know if you think this can be fixed. 😊

**Comment by odlg** [comment]
Yeah, I know there might be related stability issues. 
Is it possible to have some place in FreeShow where status with relevant info from chrome://gpu/ is visible?

**Comment by vassbo** [comment]
It's possible. I won't do it in the main application, but you can just create a new electron window in the dev environment if you want.
Example: https://github.com/bpasero/electron-gpu/blob/master/main.js
