### ISSUE TITLE
Major Performance Lag, No App Functionality

### ISSUE THREAD

**Issue by Dcanadian** [vassbo/freeshow#708]
Hello Devs, I've been super excited to see the progress that FreeShow has made in the past few months, especially as ProPresenter and other similar software go subscription only. A big thanks to all keeping this project amazing.

**The Problem**
I'm baffled, however, by the sheer lag of the software on my MacBook Air, though. Even though I'm running v1.2.1 and MacOS Sonoma 14.4.1 (the latest stable versions of both), the app refuses to function normally, and lags for minutes at a time for every. single. thing. Button's take 30+ seconds to highlight on hover, slides literally take a minute or more to appear on the outputs, and editing and creating shows is a nightmare because the changes one makes are applied over a minute after the input. (Please refer to the attached video)

From the speed and course of development, I'm guessing not many other people have this problem, but after reinstalling v1.2.1 three times, and deleting all the FreeShow folders in Finder before reinstalling, I'm not sure what else to do.

https://github.com/user-attachments/assets/5b484c6f-2678-4f98-be17-95e315a4c981

I love this software, and I want to use it at my church this weekend, but I can't do anything until this software decides to work. (Sorry, I'm a little bit frustrated) Does anyone know what the problem is, or how I can fix it?

**Recreate the Issue**
Open FreeShow (v1.2.1) and try to click on something.

**Comment by vassbo** [comment]
Hi, thank you. We are currently working on improving the performance.
Do you by any chance have a stage display set up with the "Current output" enabled?

**Comment by vassbo** [comment]
The are still active even though it's not showing up. Please go to "Stage" and disable the "Current output" items if any are active, and turn off any stage outputs you have created.
Also, please check that NDI is disabled for your outputs if you don't use that, and that you have disabled the remotes in "Connection" you don't use.

**Comment by vassbo** [comment]
Click on the light blue bar at the right.

**Comment by vassbo** [comment]
If you don't have a lot of important data you can go into the settings, click "Other" and click "Reset everything", this should make the performance fine again.

**Comment by vassbo** [comment]
There is a bug with the capture in this version causing it to stack up on itself, but should be fixed in the next version. You need to follow one of my steps above to fix it. The capture is only enabled in these scenarios:
1. A "Current output" item is set on any stage layout!
2. Any output has the NDI option enabled.
3. The "OutputShow" remote is active

Please check that all these cases are false, then restart the app and everything should work fine again!
If you can't figure it out, please reset the app data, that should also resolve the issue: https://github.com/ChurchApps/FreeShow/issues/708#issuecomment-2260595507

**Comment by vassbo** [comment]
Perfect, glad you figured it out! And thanks @thebiblelover7!
