### ISSUE TITLE
Slides view - verse, chorus tags

### ISSUE THREAD

**Issue by dajomu1** [vassbo/freeshow#75]
Should not current only show what is current in the slides and be auto updated on changes?
Also note the glitch in the "current" headline. Instead of hiding the headline I assume a scrollbar should appear? Scrollbar only appears after both "current" and "Global" are completely covered.

![image](https://user-images.githubusercontent.com/98491691/195721468-35cf9611-f82d-4c5d-85ec-caa19ac292c1.png)

**Comment by vassbo** [comment]
The current groups has to show all the groups/slides active in the show, because you have to get access to them somewhere. But it will not always show all the groups in the current layout. You can delete the groups from the show if you want to remove them.

I have noticed the text clipping, but thought it was better, scince it takes less screen space. And less need to scroll up and down all the time. But this is minor.

**Comment by dajomu1** [comment]
I deleted the slides using the groups at which the arrows point to, but they still appear in «current» which is a bit misleading or?

**Comment by vassbo** [comment]
Hmm.. maybe it's a bug then. I haven't had this issue in my testing. They should be gone when you delete them from the right menu. I'll take a closer look. Thanks.

**Comment by vassbo** [comment]
I am not able to recreate this bug. I right click on the group, and press delete, and it's gone. Does this happen all the time for you?

**Comment by dajomu1** [comment]
I can delete the way you describe, but my point is that it would be great that if I remove slide "outro" then the current view in groups should be updated to match the slides. The images in my post shows that current is no longer current. The operation has to be done twice. first delete the slide and then update the current groups view.

**Comment by vassbo** [comment]
Okay, maybe I'll add a delete button along with the remove button, in the context menu.

The thing is, because you have multiple layouts, with maybe multiple of the same verses. You many times want to remove the slide from the layout, but keep the slide in the show for future use. 😊

"Current" means all the slides stored in the show, not the slides present in the current layout.
