### ISSUE TITLE
v0.6.0 - delete verse in presentation mode

### ISSUE THREAD

**Issue by dajomu1** [vassbo/freeshow#80]
looking at the new and shiny version of Freeshow and even though the program is very good, only critique ends up here :)
I was able to import songbook from Videopsalm which is great. Thanks
Now to the point. I tried to delete a verse from a song which I opened from a project. I did not just double click on the song from "Shows". Little did I know that this would affect the song in the songbook and the verse was deleted from the song. I think this is a poor design and songs in a project should be decoupled from the source so that the source is unaffected. Source should only be altered by choosing from the bottom menu and then edit. A warning should appear informing that the source will be edited as well.

**Comment by vassbo** [comment]
No problem. Feedback is great! 😊

I have tried programs with the behavior you described, but for me the problem was the opposite, I changed a song, but I didn't realize it was just "locally".

This is what layouts are good for! (The plus/tabs in the bottom of the show.) You can arrange the verses differently, disable them, have different backgrounds, all in the same show. Selecting a layout on a show in a project will remember which one it is. 😃

Global shows are intended behavior as it makes it much easier to manage all of your shows, without creating a different version per project. Hope this is understandable.
