### ISSUE TITLE
[Bug Report] {1-2 Second Lag Across Entire App}

### ISSUE THREAD

**Issue by Dcanadian** [vassbo/freeshow#933]
**Describe the bug**
Hello @vassbo, thanks so much for the continued development of this app. After updating to 1.2.9, I've noticed that everything I do in the app takes one to two seconds to apply. For example, I'll click on something, and it will pop up after a short lag - long enough for it to feel that my computer can't keep up with what I'm doing. Or, I'll start typing the text and I'll finish the first two words before they show up in the app. Of course, this lag also applies to advancing slides, which is unacceptable in a live broadcast situation.

Investigating the problem further in Apple's Activity Monitor, I've noticed that there's a "FreeShow Activity Helper" taking up over 100% CPU. Are you able to fix this bug? Older versions aren't as laggy, and I'd love to be able to use the features in 1.2.9 without having to wait for the lag. The app itself works just fine, and I'm loving the new updates, but it's not feasible to upgrade until the performance usage is fixed.

**Reproducing**
Open FreeShow and click on a button or input text.

**Version (Optional)**
 - OS: macOS Sequoia 15.0.1
 - FreeShow Version: 1.2.9

**Comment by yurividal** [comment]
I noticed the same thing. I'm using 1.30 beta-3, and even when trying to project a simple bible passage, with no background, it takes 1 or 2 seconds to switch slides on the main screen after i press the button. This makes it hard for the church to follow a reading.

I'm running on Windows 11

**Comment by mwb9aa** [comment]
@Dcanadian and @yurividal 

I'm running Windows 11 and FreeShow Beta 3. I'm not experiencing your issue. I have Disable hardware acceleration turned on (so no hardware acceleration). You might try flipping that toggle and see if your performance improves.

**Comment by yurividal** [comment]
@mwb9aa i turned on hardware acceleration, and it did improve the overall performance of the app, but changing slides is still pretty laggy. At least one second between pressing right arrow and new slide showing on screen. (I have no animations either).
I wonder if it's due to the fact that I have over 3000 songs imported. Not sure how that affects the Bible projection though

**Comment by yurividal** [comment]
Just adding, i noticed that it runs a lot faster on my laptop, and the 1-2 seconds lag to flip slides is not present. 
The curch's computer is not old, its a 2.9Ghz i5, with 8GB of RAM and an SSD. Other software, like OpenLP, powerpoint and OpenSong run perfectly fine on it, and slide changes are instant. 
Its only freeshow, that lags severely when changing between slides.

**Comment by mwb9aa** [comment]
@yurividal 

I cannot imagine 8 GB of RAM would be enough if you have a 3000 song library plus media plus actions plus outputs, etc. Especially with an i5.  You didn't say the model number, but Intel has made i5's with 2.9 GHz clockspeed since at least [2011](https://www.intel.com/content/www/us/en/products/sku/52224/intel-core-i52410m-processor-3m-cache-up-to-2-90-ghz/specifications.html).

Are you able to get the processor model number from system information in Windows? I have almost been taken in by several computer "deals" the last couple of years only to find out I would have been getting a new computer with a 2 year-old processor.

**Comment by yurividal** [comment]
@mwb9aa I'll get the model today.
But, 3000 songs should not be loaded into Ram at the same time, if they are not in use.
If Freeshow loads every song in the library to ram, that's a pretty poor implementation...

OpenSong and Openlp, both run fine on this PC

**Comment by vassbo** [comment]
Not sure why this is, I have not had any issues with 4000+ shows (songs), so that can't be the issue! Will investigate.

**Comment by vassbo** [comment]
@Dcanadian For me at least our church has collected songs in different programs for 15+ years, so that's why I have over 4000.

**Comment by vassbo** [comment]
Recording one or more screen will reduce the performance, I don't see anything different in 1.2.9 that should affect it.

Please check this list again @Dcanadian: https://github.com/ChurchApps/FreeShow/issues/708#issuecomment-2260626296
If they are all turned off, but there is still performance issues, let me know.
If one of them are turned on, then the issue is the screen capture.
