### ISSUE TITLE
Working with templates - Blue content/header

### ISSUE THREAD

**Issue by dajomu1** [vassbo/freeshow#94]
Hi,

when I choose template Blue content or blue header, how do I get rid of them again? Seems like all other templates are replaced when choosing a different, but these two will stick no matter what. As you can see from the screenshot I have marked the bullet template, but the blue header still is present. Another strange issue is that the text is not automatically adjusted. the blue strip covers the text. 
![image](https://user-images.githubusercontent.com/98491691/215443213-332549b5-44b7-4a0f-b2ab-76bf1a483a13.png)

**Comment by vassbo** [comment]
Hi, when choosing a template with more "textboxes" than you have it will create a new one, but choosing one with just one textbox will not remove existing boxes. You can go to "Edit", and just delete it manually. But maybe I could check if the textbox is empty and another template is active, I just delete the textbox.
Also the text is not adjusted because the textbox is "behind" the box, it only adjusts to itself. 😊
